language: ruby
rvm:
  - 2.1.8

addons:
  code_climate:
    repo_token: ffeccb6ea109dc567c232e1a717b0a41a194f89ad40eea599c6f3309bf8017ee

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql
  - redis-server

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER deskspotting WITH PASSWORD 'deskspotting';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS deskspotting_test;" -U postgres
  - psql -c "CREATE DATABASE deskspotting_test ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate test:prepare

script:
  - bundle exec rspec
  - bundle exec cucumber
  - bundle exec rubocop app spec features -R --format simple

notifications:
  email:
    recipients:
      - deskspotting-dev@wolox.com.ar

cache:
  bundler: true
