class AddCollectionAccountReferenceToVenue < ActiveRecord::Migration
  def change
    add_reference :venues, :collection_account, polymorphic: true, index: false
    # I had to add the index on my own, because the index generated by rails puts this name
    # 'index_venues_on_collection_account_id_and_collection_account_type' and the db has a
    # limit of 63 characters
    add_index :venues, ["collection_account_id", "collection_account_type"],
              :unique => true, :name => 'index_venues_on_polymorphic_collection_account'
  end
end
